POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Appolinariy",
  "description": "Appolinariy description",
  "sex": "MAIL",
  "searchPreferences": "FEMALE"
}

###
GET http://localhost:8080/api/users
Accept: application/json

###
GET http://localhost:8080/api/users/99
Accept: application/json
